Wazuh-base has been fixed and improvements have been added to get better performance while building the environment

diff --git a/api/tools/env/wazuh-base/Dockerfile b/api/tools/env/wazuh-base/Dockerfile
--- a/api/tools/env/wazuh-base/Dockerfile
+++ b/api/tools/env/wazuh-base/Dockerfile
@@ -4,10 +4,11 @@ ARG WAZUH_BRANCH
 ENV DEBIAN_FRONTEND="noninteractive"
 ENV LD_LIBRARY_PATH=/var/ossec/lib
 
-RUN test -n "${WAZUH_BRANCH}"
-
 RUN apt-get update && \
-    apt-get install -y wget python3 python3-pip git gnupg2 gcc g++ cmake make vim libc6-dev curl policycoreutils automake autoconf libtool apt-transport-https lsb-release python3-cryptography sqlite3
+    apt-get install -y git wget python3 python3-pip git gnupg2 gcc g++ cmake make vim libc6-dev curl policycoreutils automake autoconf libtool apt-transport-https lsb-release python3-cryptography sqlite3 && \
+    apt-get clean
 
-RUN mkdir wazuh && curl -fSL https://github.com/wazuh/wazuh/tarball/"${WAZUH_BRANCH}" | tar zx --strip-components=1 -C wazuh
-RUN make -C /wazuh/src deps
+RUN git clone --depth 1 --branch "${WAZUH_BRANCH}" https://github.com/wazuh/wazuh.git /wazuh
+
+RUN cd /wazuh/src && \
+    make deps -j$(nproc) || (echo "First attempt failed, trying again.." && make deps)
