feat: add uninstall validation functionality to packages scripts

diff --git a/packages/debs/SPECS/wazuh-agent/debian/prerm b/packages/debs/SPECS/wazuh-agent/debian/prerm
--- a/packages/debs/SPECS/wazuh-agent/debian/prerm
+++ b/packages/debs/SPECS/wazuh-agent/debian/prerm
@@ -4,6 +4,60 @@
 set -e
 
 DIR="/var/ossec"
+VALIDATION_LOGIN=${VALIDATION_LOGIN:-""}
+VALIDATION_TOKEN=${VALIDATION_TOKEN:-""}
+
+# Function to extract package_uninstallation value from XML
+get_package_uninstallation_value() {
+  local file_path="$1"
+  local value=$(sed -n '/<anti_tampering>/,/<\/anti_tampering>/p' "$file_path" | grep -oP '(?<=<package_uninstallation>).*?(?=</package_uninstallation>)' | tr -d '\n')
+  return $value
+}
+
+# Function to check anti-tampering configuration
+check_anti_tampering() {
+  local config_file
+  local uninstall_validation_needed=""
+
+  if [ -f "${DIR}/etc/shared/agent.conf" ]; then
+    config_file="${DIR}/etc/shared/agent.conf"
+    uninstall_validation_needed=$(get_package_uninstallation_value "$config_file")
+  fi
+
+  if [ -z "$uninstall_validation_needed" ] && [ -f "${DIR}/etc/ossec.conf" ]; then
+    config_file="${DIR}/etc/ossec.conf"
+    uninstall_validation_needed=$(get_package_uninstallation_value "$config_file")
+  fi
+
+  if [ "$uninstall_validation_needed" = "yes" ]; then
+    return 1
+  else
+    return 0
+  fi
+}
+
+# Function to validate uninstallation
+validate_uninstall() {
+  local validation_command
+
+  # Validate uninstallation
+  if [ -n "$VALIDATION_TOKEN" ]; then
+    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-token ${VALIDATION_TOKEN}"
+  elif [ -n "$VALIDATION_LOGIN" ]; then
+    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-login ${VALIDATION_LOGIN}"
+  else
+    echo "Validation login or token not provided. Uninstallation cannot be continued."
+    exit 1
+  fi
+
+  $validation_command
+  if [ $? -eq 0 ]; then
+    echo "Uninstallation not authorized, aborting..."
+    exit 1
+  else
+    echo "Uninstallation authorized, continuing..."
+  fi
+}
 
 case "$1" in
     upgrade|deconfigure)
@@ -65,6 +119,11 @@ case "$1" in
 
     remove)
 
+      # Check if anti-tampering is enabled
+      if check_anti_tampering; then
+        validation_command
+      fi
+
       # Stop the services before uninstalling the package
       # Check for systemd
       if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-agent > /dev/null 2>&1; then
@@ -89,7 +148,7 @@ case "$1" in
       if [ -f ${DIR}/etc/ossec.conf ]; then
         cp -p ${DIR}/etc/ossec.conf ${DIR}/tmp/conffiles
       fi
-      
+
     ;;
 
     failed-upgrade)
