fix: some changes needed after new endpoint modifications

diff --git a/packages/debs/SPECS/wazuh-agent/debian/prerm b/packages/debs/SPECS/wazuh-agent/debian/prerm
--- a/packages/debs/SPECS/wazuh-agent/debian/prerm
+++ b/packages/debs/SPECS/wazuh-agent/debian/prerm
@@ -4,8 +4,6 @@
 set -e
 
 DIR="/var/ossec"
-VALIDATION_LOGIN=${VALIDATION_LOGIN:-""}
-VALIDATION_TOKEN=${VALIDATION_TOKEN:-""}
 
 # Function to extract package_uninstallation value from XML
 get_package_uninstallation_value() {
@@ -39,24 +37,30 @@ check_anti_tampering() {
 # Function to validate uninstallation
 validate_uninstall() {
   local validation_command
+  . "${DIR}/etc/uninstall_validation.env"
 
   # Validate uninstallation
   if [ -n "$VALIDATION_TOKEN" ] && [ -n "$VALIDATION_LOGIN" ]; then
-    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-token ${VALIDATION_TOKEN} --uninstall-auth-login ${VALIDATION_LOGIN}"
+    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-token ${VALIDATION_TOKEN} --uninstall-auth-login ${VALIDATION_LOGIN} --uninstall-auth-host ${VALIDATION_HOST}"
   elif [ -n "$VALIDATION_TOKEN" ]; then
-    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-token ${VALIDATION_TOKEN}"
+    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-token ${VALIDATION_TOKEN} --uninstall-auth-host ${VALIDATION_HOST}"
   elif [ -n "$VALIDATION_LOGIN" ]; then
-    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-login ${VALIDATION_LOGIN}"
+    validation_command="${DIR}/bin/wazuh-agentd --uninstall-auth-login ${VALIDATION_LOGIN} --uninstall-auth-host ${VALIDATION_HOST}"
   else
     echo "Validation login or token not provided. Uninstallation cannot be continued."
     exit 1
   fi
 
-  if $validation_command; then
-    echo "Uninstallation not authorized, aborting..."
-    exit 1
+  if [ -n "$VALIDATION_HOST" ]; then
+    if $validation_command; then
+      echo "Uninstallation not authorized, aborting..."
+      exit 1
+    else
+      echo "Uninstallation authorized, continuing..."
+    fi
   else
-    echo "Uninstallation authorized, continuing..."
+    echo "Validation host not provided. Uninstallation cannot be continued."
+    exit 1
   fi
 }
 
