Fix typo

diff --git a/.github/workflows/check_api_license_url.yml b/.github/workflows/check_api_license_url.yml
--- a/.github/workflows/check_api_license_url.yml
+++ b/.github/workflows/check_api_license_url.yml
@@ -32,6 +32,6 @@ jobs:
               MAJOR_MINOR_SPEC_URL=$(cat api/api/spec/spec.yaml | grep '    url: ' | grep LICENSE | cut -d '/' -f7)
               echo ${MAJOR_MINOR_SPEC_URL}
 
-          - name: Check if variable are different
+          - name: Check if variables are different
             run: |
-              if [[ ${MAJOR_MINOR_VERSION} != ${MAJOR_MINOR_SPEC_LICENSE_URL} || ${MAJOR_MINOR_VERSION} != ${MAJOR_MINOR_SPEC_LICENSE} || ${MAJOR_MINOR_SPEC_LICENSE_URL} != ${MAJOR_MINOR_SPEC_LICENSE} ]] then echo "Error comparing versions. Check API spec.yaml urls and src/VERSION"; exit 1 fi
+              if [[ ${MAJOR_MINOR_VERSION} != ${MAJOR_MINOR_SPEC_LICENSE_URL} || ${MAJOR_MINOR_VERSION} != ${MAJOR_MINOR_SPEC_LICENSE} || ${MAJOR_MINOR_SPEC_LICENSE_URL} != ${MAJOR_MINOR_SPEC_LICENSE} ]]; then echo "Error comparing versions. Check API spec.yaml urls and src/VERSION"; exit 1 fi
