Add uninstall test

diff --git a/.github/workflows/packages-build-manager.yml b/.github/workflows/packages-build-manager.yml
--- a/.github/workflows/packages-build-manager.yml
+++ b/.github/workflows/packages-build-manager.yml
@@ -103,7 +103,7 @@ jobs:
       SHOULD_UPLOAD_CHECKSUM: ${{ inputs.checksum && inputs.upload_package }}
 
     runs-on: ${{ (inputs.architecture == 'arm64' || inputs.architecture == 'aarch64') && 'wz-linux-arm64' || 'ubuntu-22.04' }}
-    timeout-minutes: 35
+    timeout-minutes: 50
     name: Build ${{ inputs.system }} wazuh-manager on ${{ inputs.architecture }}
 
     steps:
@@ -115,6 +115,9 @@ jobs:
           skip_after_successful_duplicate: "false"
 
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          tags: true
 
       - name: Set ARCH
         run: |
@@ -173,18 +176,52 @@ jobs:
         run: |
           TESTS_PATH=$GITHUB_WORKSPACE/.github/actions/test-install-components/
           if [ -z "${{ env.PACKAGE_NAME }}" ]; then echo "No package found matching the pattern!"; exit 1; fi
-          sudo docker run -v $TESTS_PATH/:/tests -v /tmp/:/packages -v /var/ossec:/var/ossec --entrypoint '/tests/install_component.sh' $CONTAINER_NAME:${{ env.TAG }} $PACKAGE_NAME manager
 
-          # Check if Wazuh was installed. The /tmp/status.log file was generated in the previous step.
+          CONTAINER_ID=$(sudo docker run -d -v $TESTS_PATH/:/tests -v /tmp/:/packages -v /var/ossec:/var/ossec \
+            --entrypoint '/bin/sh' $CONTAINER_NAME:${{ env.TAG }} -c "tail -f /dev/null")
+
+          sudo docker exec $CONTAINER_ID /tests/install_component.sh $PACKAGE_NAME manager
+
           if grep -iq " installed.*wazuh-manager" /tmp/status.log ; then
             echo "Installation successfully."
           else
             echo "The installation could not be completed. The package will not be uploaded.";
+            sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
             exit 1;
           fi
 
+          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
           echo "WAZUH_UID=$(cat $TESTS_PATH/wazuh_uid)" | tee -a $GITHUB_ENV
           echo "WAZUH_GID=$(cat $TESTS_PATH/wazuh_gid)" | tee -a $GITHUB_ENV
+      
+      - name: Check installed files
+        uses: ./.github/actions/check_files
+        with:
+          expected_files: manager_base.csv
+          wazuh_uid: ${{ env.WAZUH_UID }}
+          wazuh_gid: ${{ env.WAZUH_GID }}
+          size_check: "false"
+          ignore: "site-packages,/var/ossec/framework/python"
+
+      - name: Test uninstall built manager
+        run: |
+          if [ -z "${{ env.PACKAGE_NAME }}" ] || [ -z "${{ env.CONTAINER_ID }}" ]; then 
+            echo "No package or container found!";
+            exit 1;
+          fi
+
+          sudo docker exec $CONTAINER_ID chmod +x /tests/uninstall_component.sh
+          sudo docker exec $CONTAINER_ID /tests/uninstall_component.sh $PACKAGE_NAME manager
+
+          if grep -iq "Removing wazuh-manager" /tmp/status.log ; then
+            echo "Uninstallation successfully."
+          else
+            echo "The uninstallation could not be completed.";
+            sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
+            exit 1;
+          fi
+
+          sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
 
       - name: Upload package to GitHub
         if: always()
@@ -201,15 +238,6 @@ jobs:
           name: ${{ env.PACKAGE_SYMBOLS_NAME }}
           path: /tmp/${{ env.PACKAGE_SYMBOLS_NAME }}
           if-no-files-found: error
-
-      - name: Check installed files
-        uses: ./.github/actions/check_files
-        with:
-          expected_files: manager_base.csv
-          wazuh_uid: ${{ env.WAZUH_UID }}
-          wazuh_gid: ${{ env.WAZUH_GID }}
-          size_check: "false"
-          ignore: "site-packages,/var/ossec/framework/python"
 
       - name: Set up AWS CLI
         if: ${{ env.SHOULD_UPLOAD == 'true' }}
