Fix obtention of version in agent files

diff --git a/.github/workflows/packages-retag-images.yml b/.github/workflows/packages-retag-images.yml
--- a/.github/workflows/packages-retag-images.yml
+++ b/.github/workflows/packages-retag-images.yml
@@ -27,6 +27,7 @@ on:
       - 'main'
     paths:
       - 'VERSION.json'
+      - 'src/VERSION'
 
 jobs:
   Upload-package-building-images:
@@ -50,7 +51,17 @@ jobs:
 
       - name: Get old version from VERSION.json
         run: |
-          VERSION="$(grep '"version"' $GITHUB_WORKSPACE/VERSION.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
+          VERSION_FILE="$GITHUB_WORKSPACE/VERSION.json"
+          OLD_VERSION_FILE="$GITHUB_WORKSPACE/src/VERSION"
+          if [[ -f "$VERSION_FILE" ]]; then
+            VERSION="$(grep '"version"' $GITHUB_WORKSPACE/VERSION.json | sed -E 's/.*"version": *"([^"]+)".*/\1/')"
+          elif [[ -f "$OLD_VERSION_FILE" ]]; then
+            VERSION=$(sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\)/\1/' $GITHUB_WORKSPACE/src/VERSION)
+          else
+            echo "Error: No version file found." >&2
+            exit 1
+          fi
+
           echo "OLD_VERSION=$VERSION" >> $GITHUB_ENV;
 
       - name: Checkout repository
